sudo: required
dist: trusty

language: cpp
os: linux
compiler: gcc

branches:
  only:
    - coverity_scan

env:
  global:
    # COVERITY_SCAN_TOKEN
    - secure: "F1AnAZ0/EHvtui016Cs6QLX+Xscc/LjFeDLtwk7Z4uwsRYvc0xZSmCn64lzKL3TENo9nOZF+tl3ImgchD0DB2Qli6mEBmrB/EhtoRkWhWNU9xoD9rW1vEJUSgsJ+X4aq100yNrpsQgPtucgcyoJMwPgrvrlrT/kIi8ODpc7Per8="

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'ppa:george-edison55/cmake-3.x'
    packages:
      - gcc-5
      - g++-5
      - zlib1g-dev
      - build-essential
      - libmysqlclient-dev
      - liblua5.1-0-dev
      - cmake
  coverity_scan:
    project:
      name: pvpgn/pvpgn-server
      version: 1.99.7.2.0
      description: Player vs Player Gaming Network (PvPGN)
    build_command_prepend: mkdir build && cd build && cmake -D WITH_MYSQL=true -D WITH_LUA=true ../
    build_command: make
    branch_pattern: coverity_scan

before_install:
  - export CXX="g++-5" CC="gcc-5"
  
before_script:
  - mkdir build
  - cd build
  - cmake -D WITH_MYSQL=true -D WITH_LUA=true ../

script:
  - make

after_script:
  - sudo make install
  - sudo make uninstall
